//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class catagory
    {
        public catagory()
        {
            this.pidevices = new HashSet<pidevice>();
            this.piplayqueues = new HashSet<piplayqueue>();
        }
    
        public int idCatagory { get; set; }
    
        public virtual musik musik { get; set; }
        public virtual ICollection<pidevice> pidevices { get; set; }
        public virtual ICollection<piplayqueue> piplayqueues { get; set; }
    }
}
