//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class piindexEntities : DbContext
    {
        public piindexEntities()
            : base("name=piindexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<catagory> catagories { get; set; }
        public DbSet<musik> musiks { get; set; }
        public DbSet<pidevice> pidevices { get; set; }
        public DbSet<pifilepath> pifilepaths { get; set; }
        public DbSet<pialbum> pialbums { get; set; }
        public DbSet<piartist> piartists { get; set; }
        public DbSet<pigenre> pigenres { get; set; }
        public DbSet<pimusikdata> pimusikdatas { get; set; }
        public DbSet<piplayqueue> piplayqueues { get; set; }
    }
}
