//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pifilepath
    {
        public pifilepath()
        {
            this.pimusikdatas = new HashSet<pimusikdata>();
        }
    
        public string UUIDPath { get; set; }
        public string FilePath { get; set; }
        public string Device_UUIDDevice { get; set; }
    
        public virtual pidevice pidevice { get; set; }
        public virtual ICollection<pimusikdata> pimusikdatas { get; set; }
    }
}
