//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class filepath
    {
        public filepath()
        {
            this.musikdatas = new HashSet<musikdata>();
        }
    
        public string idFilePath { get; set; }
        public int FilePath1 { get; set; }
        public string IP_idIP { get; set; }
    
        public virtual ip ip { get; set; }
        public virtual ICollection<musikdata> musikdatas { get; set; }
    }
}
