//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMusikindex
{
    using System;
    using System.Collections.Generic;
    
    public partial class filepathtabel
    {
        public filepathtabel()
        {
            this.musikdata = new HashSet<musikdata>();
        }
    
        public int idFilesti { get; set; }
        public string FilePath { get; set; }
    
        public virtual ICollection<musikdata> musikdata { get; set; }
    }
}
