//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMusikindex
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip
    {
        public int idIP { get; set; }
        public string ejer { get; set; }
    }
}
