//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityMusikindex
{
    using System;
    using System.Collections.Generic;
    
    public partial class musikdata
    {
        public long idMusikData { get; set; }
        public string Titel { get; set; }
        public string Kunstner { get; set; }
        public string Album { get; set; }
        public string Genre { get; set; }
        public Nullable<int> nrLenth { get; set; }
        public int FilepathTabel_idFilesti { get; set; }
    
        public virtual filepathtabel filepathtabel { get; set; }
    }
}
