//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbclases
{
    using System;
    using System.Collections.Generic;
    
    public partial class catagory
    {
        public catagory()
        {
            this.devices = new HashSet<device>();
        }
    
        public int idCatagory { get; set; }
    
        public virtual ICollection<device> devices { get; set; }
        public virtual musik musik { get; set; }
        public virtual playqueue playqueue { get; set; }
    }
}
