//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbclases
{
    using System;
    using System.Collections.Generic;
    
    public partial class playqueue
    {
        public Nullable<long> MusikData_idMusikData { get; set; }
        public int Catagory_idCatagory { get; set; }
    
        public virtual catagory catagory { get; set; }
        public virtual musikdata musikdata { get; set; }
    }
}
